import type { Metadata } from "next";
import "./styles/globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import DevPanel from "@/app/demo/ui/layout/DevPanel";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <DevPanel />
        </ThemeProvider>
      </body>
    </html>
  );
}
